sudo: false
language: cpp

addons:
  apt:
    packages:
    - sdcc

script:
  - (cd ./firmware/ver1 && make clean all)
  - (cd ./firmware/ver2 && make clean all)
  - (cd ./tool && make clean all)
